quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/ProjectChatIA
quarkus.datasource.username= ${userdb}
quarkus.datasource.password= ${passdb}
quarkus.datasource.jdbc.driver= com.mysql.cj.jdbc.Driver
quarkus.hibernate-orm.database.generation=update

quarkus.langchain4j.ollama.base-url=http://localhost:11434/
quarkus.langchain4j.ollama.chat-model.model-id=minimax-m2.7:cloud